Mutual Friendship
Abidoyinsola1/ror-social-scaffold pull request #3
Opened 2020-10-26 14:15 UTC by Abidoyinsola1

Implement mutual friendship

2020-10-26 14:38 UTC, rOluochKe requested changes
Hello Team
### You did well so far :clap: However, there is an issue with the database migration, therefore, I could not finish the review. Fix the issues and submit for another code review. Good luck.
- Happy coding!

2020-10-26 14:47 UTC, Haywhizzz commented
For this project you don't need to run the rails db:create and migrate command again
those were for setting up the database which we already did when we setup the project

2020-10-26 16:02 UTC, Dandush03 requested changes
# Status: :red_circle: Request Changes :red_circle: 
### Guys sadly most of your changes were done in another PR and I cant make an inline comment in each section, so some of the issue I will point out below and other I will make it right here. Hope it makes sense

### Database Error:
_**It took me some time to find the issue on your database, but bottom line you have an error on your friendships table, you are making a bad reference and we most fix it check out [this guide](https://guides.rubyonrails.org/v3.2/migrations.html)**_

- [ ] **each file should have a reference to a table**
```ruby
# It should look more like this:
# Notice that references: refer to the table which it is linked to
# Then we assign the foreign key of that user table (since there can be more than one)
t.references :user, references: :users, foreign_key: { to_table: :users }
```
Once you fix that issue, make sure to delete your schema.rb and drop the database in order to create a clean new migration.

### Friendship confirmation (FriendshipController)
- [ ] __You're missing the user confirmation function__ Once the user creates the friendship the other user must accept it.
- [ ] __Your create function doesn't need to set confirmed:__ false since by in your database you added the default option as false :wink: 

### User Model (User)
- [ ] __In order to get all posts written by a user on their friends, students can use a simple method in the User model__
```ruby
def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
### Users view
- [ ] **Index displays all users with Friend Request button next to users who are not their friends already**

### Post View
- [ ] **index displays posts in a timeline (their own posts + posts from their friends)**

### Tests
- [ ] __Make sure you test each model/view/controller of your app.__  Right now you're missing some tests

# Happy Coding

2020-10-26 16:02 UTC, Dandush03 commented on Gemfile
> -ruby '2.7.1'
### Ruby Version:
Hey Guys!! This is a very important issue to address in any project. Whenever you change your Gemfile ruby version you have to make sure that every version that you've put in your lock file is compatible with this version, Not only that you also must change the version on your .ruby-version file since it can cause some issue when running bundler or rails server.
- [ ] **Fix your .ruby-version file**

2020-10-26 16:02 UTC, Dandush03 commented on config/database.yml
>    <<: *default
### Encript Credentials _OPTIONAL_

- [ ] __The best practice is to encrypt your credentials check [this article](https://medium.com/craft-academy/encrypted-credentials-in-ruby-on-rails-9db1f36d8570) on how to do it__

2020-10-27 10:35 UTC, maelfosso requested changes
# Changes required :red_circle:

Hello,

Thank you for implementing the suggested changes

1- There is an error when running `rails db:migrate`

```rb
PG::UndefinedColumn: ERROR:  column "friend_id" referenced in foreign key constraint does not exist
: ALTER TABLE "friendships" ADD CONSTRAINT "fk_rails_d78dc9c7fd"
FOREIGN KEY ("friend_id")
  REFERENCES "users" ("id")
```

2- The integration tests are missing. Kindly add them as required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)

For the unit tests, I suggest you use `shoulda-matchers` gem

3- I just connected as **Bob Bar** but I have the **Alice Bar**'s posts in my timeline without us being friends
![Screenshot at 2020-10-27 11:28:12](https://user-images.githubusercontent.com/8848104/97289579-aa124200-1847-11eb-8b6a-5d42d233bfbb.png)
Kindly fix that bug, please. it's required that the posts timeline includes posts written by logged-in user and their friends. Read it [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png)

3- I got this error when wanting to access to the users' list
![Screenshot at 2020-10-27 11:31:28](https://user-images.githubusercontent.com/8848104/97289842-04ab9e00-1848-11eb-9c16-2b648a85fe3b.png)

4- Kindly remove comments like this one
https://github.com/Abidoyinsola1/ror-social-scaffold/blob/9175041f02cb3ddf922540c272735bf452897545/app/models/user.rb#L16

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-10-27 16:56 UTC, tirthajyoti-ghosh commented on spec/model/comment_spec.rb
> +    end
The test statement is confusing. You are saying the comment "should save successfully" but you are testing the falseness i.e., comments "should not be saved". Please fix this.

2020-10-27 17:13 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

You have missed some of the changes requested by the previous reviewer. Let's see:

- Please add unit tests for the following models:
  * `friendship`
  * `like`
  
  Don't forget to add tests for both validations and associations. You can use `shoulda-matchers` gem for unit tests. The gem takes care of both positive and negative scenarios. This is just a suggestion. You are free to use whatever you want. Just remember to test both positive and negative scenarios.

- There are some confusing test statements in `spec/model/comment_spec.rb` and `spec/model/post_spec.rb`. I have pointed them out in the comments below. Be sure to check them out.

- Please add association tests for the following models:
  * `comment`
  * `user`
  * `post`

  You can use `should-matchers`. But you are free to use whatever you want. Just remember to test both positive and negative scenarios.

- As requested by the previous reviewer, please add integration tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-10-27 20:42 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 

Hi Team! :wave: 

Good job in your attempt to address all the changes.
While I am not COMPLETELY happy with the integration tests (You should separate them to their respective names, user_controller_spec.rb etc) and you should add more. You have attempted integration tests and have gone through quite a few iterations of reviews at this point!

So it's a pass from me! But please add more integration tests moving forward!

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-10-28 07:50 UTC, merged